import { mkdir, readFile, realpath, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import {
  RUNTIME_ASSET_MANIFEST_SCHEMA_VERSION,
  validateRuntimeAssetManifestData,
  type RuntimeAssetManifestData,
  type RuntimeAssetManifestEntry,
} from "../src/data/schemas.js";
import { writeJsonFile } from "./lib/write-json.js";
import sharp from "sharp";

type RuntimeAssetSourceEntry = {
  slug: string;
  sourceCategory: "pokemon" | "item";
  sourcePath: string;
  runtimePath: string;
};

type RuntimeAssetSourcesData = {
  schemaVersion: "runtime-asset-sources.v1";
  assets: RuntimeAssetSourceEntry[];
};

const projectRoot = process.cwd();
const sourceReportPath = "generated/reports/runtime-asset-sources.json";
const outputRoot = "generated/assets/runtime";
const manifestOutputPath = `${outputRoot}/asset-manifest.json`;
const rawSourceRoot = resolve(projectRoot, "docs/pokopia_image_sources");
const webpQuality = 82;
const maxPokemonEdge = 420;
const maxItemEdge = 240;
const runtimeImageTotalLimit = 15 * 1024 * 1024;
const runtimePokemonImageLimit = 64 * 1024;
const runtimeItemImageLimit = 32 * 1024;

const sourceReport = JSON.parse(await readFile(resolve(projectRoot, sourceReportPath), "utf8")) as RuntimeAssetSourcesData;
validateSourceReport(sourceReport);
validateUniqueRuntimePaths(sourceReport.assets);

await rm(resolve(projectRoot, outputRoot), { recursive: true, force: true });

const manifestEntries = await Promise.all(sourceReport.assets.map(copyRuntimeAsset));
const sortedEntries = manifestEntries.sort(compareManifestEntries);
const totalBytes = sortedEntries.reduce((sum, entry) => sum + entry.byteSize, 0);
if (totalBytes >= runtimeImageTotalLimit) {
  throw new Error(`Runtime image total exceeds ${runtimeImageTotalLimit} byte budget: ${totalBytes}`);
}
const manifest: RuntimeAssetManifestData = {
  schemaVersion: RUNTIME_ASSET_MANIFEST_SCHEMA_VERSION,
  generatedFrom: {
    sourceReportPath,
    rawBoundary: "docs/pokopia_image_sources/**",
  },
  summary: {
    assetCount: sortedEntries.length,
    pokemonCount: sortedEntries.filter((entry) => entry.sourceCategory === "pokemon").length,
    itemCount: sortedEntries.filter((entry) => entry.sourceCategory === "item").length,
    totalBytes,
  },
  assets: sortedEntries,
};

const issues = validateRuntimeAssetManifestData(manifest);
if (issues.length > 0) {
  throw new Error(`Runtime asset manifest validation failed: ${issues.slice(0, 5).map((issue) => `${issue.path} ${issue.message}`).join("; ")}`);
}

await writeJsonFile(resolve(projectRoot, manifestOutputPath), manifest);
console.log(
  `Generated ${manifestOutputPath} with ${manifest.summary.assetCount} assets (${manifest.summary.totalBytes} bytes).`,
);

function validateSourceReport(data: RuntimeAssetSourcesData): void {
  if (data.schemaVersion !== "runtime-asset-sources.v1" || !Array.isArray(data.assets)) {
    throw new Error(`${sourceReportPath} must be generated by npm run generate:data before runtime assets are generated.`);
  }
}

async function copyRuntimeAsset(entry: RuntimeAssetSourceEntry): Promise<RuntimeAssetManifestEntry> {
  validateRuntimePath(entry);
  validateRuntimePathExtension(entry);
  const sourcePath = await validatedSourcePath(entry);
  const result = await optimizeRuntimeAsset(sourcePath, entry.sourceCategory);
  validateOptimizedRuntimeAsset(entry, result);
  const outputPath = resolve(projectRoot, outputRoot, entry.runtimePath.replace(/^\/assets\/runtime\//, ""));
  const outputRelativePath = relative(resolve(projectRoot, outputRoot), outputPath);
  if (outputRelativePath.startsWith("..") || isAbsolute(outputRelativePath)) {
    throw new Error(`Runtime asset path escapes output root: ${entry.runtimePath}`);
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, result.bytes);
  return {
    slug: entry.slug,
    sourceCategory: entry.sourceCategory,
    runtimePath: entry.runtimePath,
    byteSize: result.bytes.length,
    contentType: "image/webp",
    width: result.width,
    height: result.height,
  };
}

async function optimizeRuntimeAsset(
  sourcePath: string,
  sourceCategory: RuntimeAssetSourceEntry["sourceCategory"],
): Promise<{ bytes: Buffer; width: number; height: number }> {
  const maxEdge = sourceCategory === "pokemon" ? maxPokemonEdge : maxItemEdge;
  const { data, info } = await sharp(sourcePath, { animated: false })
    .rotate()
    .resize({
      width: maxEdge,
      height: maxEdge,
      fit: "inside",
      withoutEnlargement: true,
    })
    .webp({ quality: webpQuality })
    .toBuffer({ resolveWithObject: true });
  return { bytes: data, width: info.width, height: info.height };
}

function validateRuntimePath(entry: RuntimeAssetSourceEntry): void {
  const expectedPrefix = entry.sourceCategory === "pokemon" ? "/assets/runtime/pokemon/" : "/assets/runtime/items/";
  if (!entry.runtimePath.startsWith(expectedPrefix) || entry.runtimePath.includes("..") || entry.runtimePath.includes("\\")) {
    throw new Error(`Invalid runtime asset path for ${entry.sourceCategory}:${entry.slug}: ${entry.runtimePath}`);
  }
  if (!entry.sourcePath.startsWith("docs/pokopia_image_sources/") || entry.sourcePath.includes("..") || entry.sourcePath.includes("\\")) {
    throw new Error(`Invalid source asset path for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
}

async function validatedSourcePath(entry: RuntimeAssetSourceEntry): Promise<string> {
  const sourcePath = resolve(projectRoot, entry.sourcePath);
  const [rootRealPath, sourceRealPath, sourceStat] = await Promise.all([
    realpath(rawSourceRoot),
    realpath(sourcePath),
    stat(sourcePath),
  ]);
  const rootRelativePath = relative(rootRealPath, sourceRealPath);
  if (rootRelativePath.startsWith("..") || isAbsolute(rootRelativePath)) {
    throw new Error(`Runtime asset source escapes raw source root for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
  if (!sourceStat.isFile()) {
    throw new Error(`Runtime asset source must be a file for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
  return sourceRealPath;
}

function validateRuntimePathExtension(entry: RuntimeAssetSourceEntry): void {
  if (!entry.runtimePath.endsWith(".webp")) {
    throw new Error(
      `Runtime asset path for ${entry.sourceCategory}:${entry.slug} must use .webp output: ${entry.runtimePath}`,
    );
  }
}

function validateOptimizedRuntimeAsset(
  entry: RuntimeAssetSourceEntry,
  result: { bytes: Buffer; width: number; height: number },
): void {
  const byteLimit = entry.sourceCategory === "pokemon" ? runtimePokemonImageLimit : runtimeItemImageLimit;
  if (result.bytes.length >= byteLimit) {
    throw new Error(
      `Runtime asset ${entry.sourceCategory}:${entry.slug} exceeds ${byteLimit} byte budget after optimization: ${result.bytes.length}`,
    );
  }
  const edgeLimit = entry.sourceCategory === "pokemon" ? maxPokemonEdge : maxItemEdge;
  if (Math.max(result.width, result.height) > edgeLimit) {
    throw new Error(
      `Runtime asset ${entry.sourceCategory}:${entry.slug} exceeds ${edgeLimit}px edge budget after optimization: ${result.width}x${result.height}`,
    );
  }
}

function validateUniqueRuntimePaths(assets: RuntimeAssetSourceEntry[]): void {
  const seen = new Map<string, RuntimeAssetSourceEntry>();
  assets.forEach((asset) => {
    const duplicate = seen.get(asset.runtimePath);
    if (duplicate) {
      throw new Error(
        `Duplicate runtimePath ${asset.runtimePath} for ${duplicate.sourceCategory}:${duplicate.slug} and ${asset.sourceCategory}:${asset.slug}`,
      );
    }
    seen.set(asset.runtimePath, asset);
  });
}

function compareManifestEntries(left: RuntimeAssetManifestEntry, right: RuntimeAssetManifestEntry): number {
  return (
    left.sourceCategory.localeCompare(right.sourceCategory, "en") ||
    left.slug.localeCompare(right.slug, "en") ||
    left.runtimePath.localeCompare(right.runtimePath, "en")
  );
}
