import { mkdir, readFile, realpath, rm, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import {
  RUNTIME_ASSET_MANIFEST_SCHEMA_VERSION,
  validateRuntimeAssetManifestData,
  type RuntimeAssetManifestData,
  type RuntimeAssetManifestEntry,
} from "../src/data/schemas.js";
import { writeJsonFile } from "./lib/write-json.js";

type RuntimeAssetSourceEntry = {
  slug: string;
  sourceCategory: "pokemon" | "item";
  sourcePath: string;
  runtimePath: string;
};

type RuntimeAssetSourcesData = {
  schemaVersion: "runtime-asset-sources.v1";
  assets: RuntimeAssetSourceEntry[];
};

const projectRoot = process.cwd();
const sourceReportPath = "generated/reports/runtime-asset-sources.json";
const outputRoot = "generated/assets/runtime";
const manifestOutputPath = `${outputRoot}/asset-manifest.json`;
const rawSourceRoot = resolve(projectRoot, "docs/pokopia_image_sources");

const sourceReport = JSON.parse(await readFile(resolve(projectRoot, sourceReportPath), "utf8")) as RuntimeAssetSourcesData;
validateSourceReport(sourceReport);

await rm(resolve(projectRoot, outputRoot), { recursive: true, force: true });

const manifestEntries = await Promise.all(sourceReport.assets.map(copyRuntimeAsset));
const sortedEntries = manifestEntries.sort(compareManifestEntries);
const manifest: RuntimeAssetManifestData = {
  schemaVersion: RUNTIME_ASSET_MANIFEST_SCHEMA_VERSION,
  generatedFrom: {
    sourceReportPath,
    rawBoundary: "docs/pokopia_image_sources/**",
  },
  summary: {
    assetCount: sortedEntries.length,
    pokemonCount: sortedEntries.filter((entry) => entry.sourceCategory === "pokemon").length,
    itemCount: sortedEntries.filter((entry) => entry.sourceCategory === "item").length,
    totalBytes: sortedEntries.reduce((sum, entry) => sum + entry.byteSize, 0),
  },
  assets: sortedEntries,
};

const issues = validateRuntimeAssetManifestData(manifest);
if (issues.length > 0) {
  throw new Error(`Runtime asset manifest validation failed: ${issues.slice(0, 5).map((issue) => `${issue.path} ${issue.message}`).join("; ")}`);
}

await writeJsonFile(resolve(projectRoot, manifestOutputPath), manifest);
console.log(
  `Generated ${manifestOutputPath} with ${manifest.summary.assetCount} assets (${manifest.summary.totalBytes} bytes).`,
);

function validateSourceReport(data: RuntimeAssetSourcesData): void {
  if (data.schemaVersion !== "runtime-asset-sources.v1" || !Array.isArray(data.assets)) {
    throw new Error(`${sourceReportPath} must be generated by npm run generate:data before runtime assets are generated.`);
  }
}

async function copyRuntimeAsset(entry: RuntimeAssetSourceEntry): Promise<RuntimeAssetManifestEntry> {
  validateRuntimePath(entry);
  const sourcePath = await validatedSourcePath(entry);
  const bytes = await readFile(sourcePath);
  const contentType = contentTypeFromBytes(bytes);
  validateRuntimePathExtension(entry, contentType);
  const outputPath = resolve(projectRoot, outputRoot, entry.runtimePath.replace(/^\/assets\/runtime\//, ""));
  const outputRelativePath = relative(resolve(projectRoot, outputRoot), outputPath);
  if (outputRelativePath.startsWith("..") || isAbsolute(outputRelativePath)) {
    throw new Error(`Runtime asset path escapes output root: ${entry.runtimePath}`);
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, bytes);
  return {
    slug: entry.slug,
    sourceCategory: entry.sourceCategory,
    runtimePath: entry.runtimePath,
    byteSize: bytes.length,
    contentType,
    width: null,
    height: null,
  };
}

function validateRuntimePath(entry: RuntimeAssetSourceEntry): void {
  const expectedPrefix = entry.sourceCategory === "pokemon" ? "/assets/runtime/pokemon/" : "/assets/runtime/items/";
  if (!entry.runtimePath.startsWith(expectedPrefix) || entry.runtimePath.includes("..") || entry.runtimePath.includes("\\")) {
    throw new Error(`Invalid runtime asset path for ${entry.sourceCategory}:${entry.slug}: ${entry.runtimePath}`);
  }
  if (!entry.sourcePath.startsWith("docs/pokopia_image_sources/") || entry.sourcePath.includes("..") || entry.sourcePath.includes("\\")) {
    throw new Error(`Invalid source asset path for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
}

async function validatedSourcePath(entry: RuntimeAssetSourceEntry): Promise<string> {
  const sourcePath = resolve(projectRoot, entry.sourcePath);
  const [rootRealPath, sourceRealPath, sourceStat] = await Promise.all([
    realpath(rawSourceRoot),
    realpath(sourcePath),
    stat(sourcePath),
  ]);
  const rootRelativePath = relative(rootRealPath, sourceRealPath);
  if (rootRelativePath.startsWith("..") || isAbsolute(rootRelativePath)) {
    throw new Error(`Runtime asset source escapes raw source root for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
  if (!sourceStat.isFile()) {
    throw new Error(`Runtime asset source must be a file for ${entry.sourceCategory}:${entry.slug}: ${entry.sourcePath}`);
  }
  return sourceRealPath;
}

function validateRuntimePathExtension(entry: RuntimeAssetSourceEntry, contentType: string): void {
  const expectedExtension = extensionForContentType(contentType);
  if (expectedExtension === null) {
    throw new Error(`Unsupported runtime asset content type for ${entry.sourceCategory}:${entry.slug}: ${contentType}`);
  }
  if (!entry.runtimePath.endsWith(expectedExtension)) {
    throw new Error(
      `Runtime asset extension does not match content for ${entry.sourceCategory}:${entry.slug}: ${entry.runtimePath} should end with ${expectedExtension}`,
    );
  }
}

function contentTypeFromBytes(bytes: Buffer): string {
  if (bytes.length >= 12 && bytes.toString("ascii", 0, 4) === "RIFF" && bytes.toString("ascii", 8, 12) === "WEBP") {
    return "image/webp";
  }
  if (bytes.length >= 8 && bytes[0] === 0x89 && bytes.toString("ascii", 1, 4) === "PNG") {
    return "image/png";
  }
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "image/jpeg";
  }
  if (bytes.length >= 6 && (bytes.toString("ascii", 0, 6) === "GIF87a" || bytes.toString("ascii", 0, 6) === "GIF89a")) {
    return "image/gif";
  }
  return "application/octet-stream";
}

function extensionForContentType(contentType: string): string | null {
  switch (contentType) {
    case "image/webp":
      return ".webp";
    case "image/png":
      return ".png";
    case "image/jpeg":
      return ".jpg";
    case "image/gif":
      return ".gif";
    default:
      return null;
  }
}

function compareManifestEntries(left: RuntimeAssetManifestEntry, right: RuntimeAssetManifestEntry): number {
  return (
    left.sourceCategory.localeCompare(right.sourceCategory, "en") ||
    left.slug.localeCompare(right.slug, "en") ||
    left.runtimePath.localeCompare(right.runtimePath, "en")
  );
}
